language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  composer install

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS kartta;'
  - mysql kartta < db/import.sql
script: phpunit tests/SchoolTest.php